#!/bin/bash
#
# bootstrap
#
# Checks for dependencies so you can get rolling with ActiveCell straight away

echo ""
echo "  Striker"
echo "  Bad-ass, greasy-fast, cached calculated collections"
echo ""

#
# Check for node
#
if test ! $(which node); then
  echo "  x You need to install node. If you use Homebrew, you can run:"
  echo "    brew install node"
  exit
else
  echo "  + node found."
fi

#
# Check node version
#
NODE_VERSION=$(node -v)
if ! [[ $NODE_VERSION == v0.10* ]]; then
  echo "  x You need to update node to 0.10.x. If you use Homebrew, you can run:"
  echo "    brew update && brew upgrade node"
  exit
else
  echo "  + node >= 0.10."
fi

#
# Check for npm
#
if test ! $(which npm); then
  echo "  x You need to install npm. If you use Homebrew, you can run:"
  echo "    brew install npm"
  exit
else
  echo "  + npm found."
fi

#
# Check for phantomjs
#
if test ! $(which phantomjs); then
  echo "  x You need to install phantomjsm. If you use Homebrew, you can run:"
  echo "    brew install phantomjs"
  exit
else
  echo "  + phantomjs found."
fi

#
# Install from packages
#
echo ""
echo "  Installing from package.json"
echo ""
npm install
